name: Build & Deploy on Self-Hosted Runner

on:
  push:
    branches: [main]
  workflow_dispatch:  # ✅ Manual trigger enabled here


jobs:
  deploy:
    runs-on: self-hosted  # 🔥 KEY: this tells GitHub to use YOUR machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t custom-flask-app:latest ./app

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Remove redis_data from Terraform state if it doesn't exist
        run:  terraform state rm docker_volume.redis_data || true

      - name: Terraform Plan
        run:  terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

  destroy:
    runs-on: self-hosted
    needs: [deploy]           # optional: makes destroy wait for deploy if run together
    if: github.event_name == 'workflow_dispatch'  # Manual only

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
