name: Manual Destroy

on:
  workflow_dispatch:  # ✅ Only manual trigger

jobs:
  destroy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init

      - name: Manual Docker cleanup
        run: |
            docker rm -f flask-container redis_container nginx_container || true
            docker volume rm redis_data || true
            docker network rm dev_network || true


      - name: Terraform Destroy
        run: terraform destroy -auto-approve
